# Saving and sharing NumPy arrays

## Introduction

This notebook will show how to store NumPy arrays as zipped files and human-readable files like `*.csv` and how to load these data back into a NumPy workspace environment anywhere enabling data portability.

## Objectives

Two very commonly used format of data transfer between machines will be shown here (compressed zip files and csv files) both for reading and writing purposes that will serve typical storage needs in NumPy. The steps below are followed in order to reach our objectives

* create two 1D arrays and one 2D array
* save these arrays to files
* remove variables from workspace
* load the variables from saved file
* compare zipped binary files to human-readable delimited files
* finish with the skills of saving, loading, and sharing NumPy arrays

In [1]:
import numpy as np

In [2]:
x = np.arange(0, 10, 1)
y = x ** 2
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [3]:
np.savez('data/x_y-squared.npz', x_axis=x, y_axis=y)

In [4]:
del x, y

In [5]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from 'e:\<...>ges\\numpy\\__init__.py'>
os         module    <module 'os' from 'c:\\us<...>n\\python39\\lib\\os.py'>
sys        module    <module 'sys' (built-in)>


In [6]:
load_xy = np.load('data/x_y-squared.npz')
print(load_xy.files)

['x_axis', 'y_axis']


In [7]:
%whos

Variable   Type       Data/Info
-------------------------------
load_xy    NpzFile    <numpy.lib.npyio.NpzFile <...>ct at 0x00000215DF535DC0>
np         module     <module 'numpy' from 'e:\<...>ges\\numpy\\__init__.py'>
os         module     <module 'os' from 'c:\\us<...>n\\python39\\lib\\os.py'>
sys        module     <module 'sys' (built-in)>


In [8]:
x = load_xy['x_axis']
y = load_xy['y_axis']
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [9]:
array_out = np.block([x[:, np.newaxis], y[:, np.newaxis]])
print('array with shape', array_out.shape)
array_out

array with shape (10, 2)


array([[ 0,  0],
       [ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36],
       [ 7, 49],
       [ 8, 64],
       [ 9, 81]])

In [10]:
np.savetxt('data/x_y-squared.csv', X=array_out, header='x, y', delimiter=',')

In [11]:
del x, y

In [12]:
load_xy = np.loadtxt('data/x_y-squared.csv', delimiter=',')
load_xy.shape

(10, 2)

In [13]:
x = load_xy[:, 0]
y = load_xy[:, 1]
print(x)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
